AUTHELIA-LOGOUT: https://auth.SAMPLE-DOMAIN.org
AUTHENTICATION: FLASK-LOGIN
FLASK:
  DEBUG: false
  HOST: 0.0.0.0
  PORT: '5000'
  SECRET: abcd1234
  TEMPLATES_AUTO_RELOAD: true
  USE_RELOADER: false
PRIMARY-COLOR: '#C0A890'
PRINT_TEMPLATE:
  ADD_DESCRIPTION_TO_LABEL: true
  ADD_LOGO_TO_QR: true
  COLORED_BACKGROUNDS: true
  DESCRIPTION_FONT_SIZE: 0.35cm
  IDENTIFIER: AVERY L7164
  ID_FONT_SIZE: 0.8cm
  LABEL:
    HEIGHT: 7.2cm
    WIDTH: 6.353cm
    X_GUTTER: 0.25cm
    X_PADDING: 0.25cm
    Y_GUTTER: 0cm
    Y_PADDING: 0.1cm
  LABELS_PER_PAGE: 12
  PAGE:
    WIDTH: 21cm
    X_MARGIN: 0.7214cm
    Y_MARGIN: 0.457cm
  QR_HEIGHT: 4.3cm
SITE:
  BASE_URL: http://localhost
  PATH_PREFIX: /
USERS:
  artem:
    LOCATION_SORTING: 3
    password: pass
  default: {}
